module: CouchDB
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-CouchDB/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-CouchDB.xcodeproj, -target, CouchDB, LIBRARY_SEARCH_PATHS=.build/debug]
